### ISSUE TITLE
Difference between heroku-cli and heroku-cli-bin

### ISSUE THREAD

**Issue by xeoneux** [SampsonCrowley/arch_packages#12]
Hi, I didn't quite catch the difference between the heroku-cli and heroku-cli-bin packages since they are the same versions and have the same deps?

**Comment by ahmubashshir** [comment]
-bin suffix means this package is built from the binary released upstream.

**Comment by SampsonCrowley** [comment]
@ahmubashshir is correct

this is also a __very__ well known convention in the arch ecosystem
