### ISSUE TITLE
Cannot build heroku-cli package with pikaur and yay on Android.

### ISSUE THREAD

**Issue by SDRausty** [SampsonCrowley/arch_packages#6]
Hi @SampsonCrowley;  Thank you for making these Arch Linux packages available.

Issues have been found with `heroku-cli`, ["cannot build heroku-cli package with pikaur and yay"](https://github.com/TermuxArch/TermuxArch/issues/22#issuecomment-686504794) when attempting to build in Arch Linux in PRoot on an Android smartphone:

1) aarch64: `chown: changing ownership of '/home/xd003/.cache/yay/heroku-cli/pkg/heroku-cli/usr/lib/node_modules/heroku/LICENSE': Operation not permitted`
2) armv7l: `npm                                                             
Illegal instruction`

Insight regarding these issues is welcome.

**Comment by SampsonCrowley** [comment]
You have a permissions issue with your cache folder. This isn't a problem
with the PKGBUILD

**Comment by SampsonCrowley** [comment]
@SDRausty this PKGBUILD does nothing but run`npm install` in a way that is compatible with the arch build system, and then fixes some permissions for security. 

You getting an `npm Illegal instruction` is a compatibility problem with `npm` and whatever you're doing with PRoot. It's not something I can fix here.

If you have a workaround for your specific environment that won't break things for everyone else using supported environments I'd be happy to accept a PR

**Comment by SDRausty** [comment]
Many packages do build with `pikaur` and `yay` in Arch Linux in PRoot without errors.  ~~On armv7l Arch Linux `npm` does not work.  Understanding why `npm` malfunctions on armv7l when building  is welcome.~~

> permissions issue with your cache folder. 

Do you have any idea why this permission error occurs on aarch64 with the .cache directory?

>  a workaround for your specific environment

The Arch Linux environment in Android is established with https://termuxarch.github.io/TermuxArch/.  I would be happy to submit a pull request, but I do not know what is causing this issue, only its effects; This is why I opened it.

**Comment by SampsonCrowley** [comment]
Did you install a version of node compatible with ARMv7? aarch64 and armv7h are different architectures

**Comment by SampsonCrowley** [comment]
Just because other packages support arm, doesn't mean all do. If you notice in this package, the only listed supported architecture is `x86_64`

**Comment by SampsonCrowley** [comment]
https://wiki.archlinux.org/index.php/PKGBUILD#arch

**Comment by SampsonCrowley** [comment]
@SDRausty https://github.com/nodejs/node/issues/5495

**Comment by SDRausty** [comment]
@SampsonCrowley Thank you for expanding your answer.

> Did you install a version of node compatible with ARMv7? 

Nodejs works on armv7l in Termux, but not in Arch Linux in Termux PRoot.

**Comment by SampsonCrowley** [comment]
@SDRausty I just pushed up the PKGBUILD that should be compatible with ARM

**Comment by ghost** [comment]
@SampsonCrowley not sure if the new commit is breaking the validity check.

==> Validating source_x86_64 files with sha256sums...
    heroku-v7.42.13-linux-x64.tar.xz ... FAILED
==> ERROR: One or more files did not pass the validity check!

I'm on Arch Linux x86_64, Kernel: 5.8.5-arch1-1

**Comment by SampsonCrowley** [comment]
There shouldn't be any source_x86_64 sources...
